import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { getAuthUserFromRequest } from "@/lib/salaryWallet";
import { authorizeErpRequest, erpErrorResponse, getErpAccessByDiscordId } from "@/lib/erpAccess";
import { ERP_ROLES, canManageTargetRole, normalizeErpRole } from "@/lib/erpRoles";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const ORGANIZATION = "qiunai";
const LEGACY_ADMIN_TABLE = "qiunai_admins";
async function syncLegacyAdmin(discordId, displayName, role) { const active = role !== "employee"; const { data: existing, error: readError } = await supabaseAdmin.from(LEGACY_ADMIN_TABLE).select("id").eq("discord_id", discordId).maybeSingle(); if (readError) throw readError; if (existing) { const { error } = await supabaseAdmin.from(LEGACY_ADMIN_TABLE).update({ name: displayName || discordId, is_active: active }).eq("id", existing.id); if (error) throw error; return; } if (!active) return; const { error } = await supabaseAdmin.from(LEGACY_ADMIN_TABLE).insert({ discord_id: discordId, name: displayName || discordId, is_active: true }); if (error) throw error; }
async function listAccounts() { const { data, error } = await supabaseAdmin.from("erp_role_assignments").select("id, discord_id, display_name, role, is_active, created_at, updated_at").eq("organization_code", ORGANIZATION).order("created_at", { ascending: true }); if (error) throw error; return data || []; }
async function mutateAccount(request) { const actor = await authorizeErpRequest(supabaseAdmin, request, ORGANIZATION, "canManageRoles"); const body = await request.json().catch(() => ({})); const discordId = String(body.discordId || "").trim(); const displayName = String(body.displayName || "").trim().slice(0, 100); const role = normalizeErpRole(body.role); if (!/^\d{15,22}$/.test(discordId)) throw new Error("請輸入正確的 Discord 帳號 ID"); if (!ERP_ROLES.includes(role)) throw new Error("ERP 權限層級不正確"); if (discordId === actor.discordId) throw new Error("為避免鎖住後台，不能變更自己目前的權限"); const { data: existing, error: existingError } = await supabaseAdmin.from("erp_role_assignments").select("role, display_name").eq("organization_code", ORGANIZATION).eq("discord_id", discordId).maybeSingle(); if (existingError) throw existingError; if (existing && !canManageTargetRole(actor.role, existing.role)) throw new Error("你不能變更同階或更高階帳號"); if (!canManageTargetRole(actor.role, role)) throw new Error("你不能指派這個 ERP 權限層級"); const { data, error } = await supabaseAdmin.from("erp_role_assignments").upsert({ organization_code: ORGANIZATION, discord_id: discordId, display_name: displayName || existing?.display_name || discordId, role, is_active: true, created_by: actor.discordId, updated_by: actor.discordId, updated_at: new Date().toISOString() }, { onConflict: "organization_code,discord_id" }).select("*").single(); if (error) throw error; await syncLegacyAdmin(discordId, data.display_name, role); return data; }
export async function GET(request) { try { const auth = await getAuthUserFromRequest(supabaseAdmin, request); const access = await getErpAccessByDiscordId(supabaseAdmin, ORGANIZATION, auth.discordId); const url = new URL(request.url); if (url.searchParams.get("accounts") === "1") { if (!access.capabilities.canManageRoles) return NextResponse.json({ ok: false, message: "你沒有權限管理帳號" }, { status: 403 }); return NextResponse.json({ ok: true, access, accounts: await listAccounts() }); } return NextResponse.json({ ok: true, access }); } catch (error) { return erpErrorResponse(error); } }
export async function POST(request) { try { return NextResponse.json({ ok: true, account: await mutateAccount(request) }); } catch (error) { return erpErrorResponse(error, "新增 ERP 帳號失敗"); } }
export async function PATCH(request) { try { return NextResponse.json({ ok: true, account: await mutateAccount(request) }); } catch (error) { return erpErrorResponse(error, "更新 ERP 權限失敗"); } }

