"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Loader2, Save, ShieldCheck, UserCog } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { ERP_ROLE_LABELS, ERP_ROLES, canManageTargetRole } from "@/lib/erpRoles";
type Role = keyof typeof ERP_ROLE_LABELS;
type Account = { id: string; discord_id: string; display_name?: string | null; role: Role; is_active: boolean };
type Access = { discordId: string; role: Role; capabilities: { canManageRoles: boolean; canAssignPrivilegedRoles: boolean } };
export default function ErpAccessManager({ apiPath, accent = "pink" }: { apiPath: string; accent?: "sky" | "pink" }) {
  const [accounts, setAccounts] = useState<Account[]>([]); const [access, setAccess] = useState<Access | null>(null); const [loading, setLoading] = useState(true); const [savingId, setSavingId] = useState<string | null>(null); const [discordId, setDiscordId] = useState(""); const [displayName, setDisplayName] = useState(""); const [role, setRole] = useState<Role>("customer_service");
  const theme = accent === "pink" ? { border: "border-pink-100", soft: "bg-pink-50", button: "bg-pink-500 hover:bg-pink-600", text: "text-pink-600" } : { border: "border-sky-100", soft: "bg-sky-50", button: "bg-sky-500 hover:bg-sky-600", text: "text-sky-600" };
  const getToken = useCallback(async () => { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("請重新登入 ERP"); return data.session.access_token; }, []);
  const load = useCallback(async () => { setLoading(true); try { const token = await getToken(); const response = await fetch(`${apiPath}?accounts=1`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "讀取 ERP 權限失敗"); setAccounts(payload.accounts || []); setAccess(payload.access || null); } catch (error) { alert(error instanceof Error ? error.message : "讀取 ERP 權限失敗"); } finally { setLoading(false); } }, [apiPath, getToken]);
  useEffect(() => {
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, [load]);
  const assignableRoles = useMemo(() => ERP_ROLES.filter((item) => canManageTargetRole(access?.role, item)) as Role[], [access?.role]);
  async function saveAccount(account?: Account) { const targetId = account?.discord_id || discordId.trim(); const targetName = account?.display_name || displayName.trim(); const targetRole = account?.role || role; setSavingId(targetId || "new"); try { const token = await getToken(); const response = await fetch(apiPath, { method: account ? "PATCH" : "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ discordId: targetId, displayName: targetName, role: targetRole }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "儲存 ERP 權限失敗"); setDiscordId(""); setDisplayName(""); setRole("customer_service"); await load(); } catch (error) { alert(error instanceof Error ? error.message : "儲存 ERP 權限失敗"); } finally { setSavingId(null); } }
  function updateLocal(id: string, key: "display_name" | "role", value: string) { setAccounts((items) => items.map((item) => item.id === id ? { ...item, [key]: value } : item)); }
  return <section className={`rounded-[30px] border bg-white p-5 shadow-sm sm:p-6 ${theme.border}`}><div className="flex items-start gap-3"><span className={`rounded-2xl p-3 ${theme.soft} ${theme.text}`}><ShieldCheck size={22}/></span><div><h2 className="text-xl font-black text-slate-900">ERP 帳號與權限</h2><p className="mt-1 text-sm leading-6 text-slate-500">最高管理員可指派全部層級；店經理只能管理客服與員工帳號。</p></div></div>
    {loading ? <p className="mt-5 flex items-center gap-2 text-sm text-slate-400"><Loader2 size={17} className="animate-spin"/>讀取帳號中…</p> : <><div className={`mt-5 grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_1fr_180px_auto] ${theme.border} ${theme.soft}`}><input value={discordId} onChange={(event) => setDiscordId(event.target.value.replace(/\D/g, ""))} placeholder="Discord 帳號 ID" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"/><input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="顯示名稱" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"/><select value={role} onChange={(event) => setRole(event.target.value as Role)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5">{assignableRoles.map((item) => <option key={item} value={item}>{ERP_ROLE_LABELS[item]}</option>)}</select><button type="button" onClick={() => void saveAccount()} disabled={!discordId || savingId !== null} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 font-black text-white disabled:opacity-40 ${theme.button}`}><UserCog size={17}/>新增帳號</button></div>
      <div className="mt-5 space-y-3">{accounts.map((account) => { const editable = account.discord_id !== access?.discordId && canManageTargetRole(access?.role, account.role); return <article key={account.id} className={`grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_1fr_180px_auto] md:items-center ${theme.border}`}><div className="min-w-0"><p className="truncate font-black text-slate-800">{account.display_name || account.discord_id}</p><p className="mt-1 text-xs text-slate-400">{account.discord_id}</p></div><input value={account.display_name || ""} onChange={(event) => updateLocal(account.id, "display_name", event.target.value)} disabled={!editable} className="rounded-xl border border-slate-200 px-3 py-2 disabled:bg-slate-50 disabled:text-slate-400"/><select value={account.role} onChange={(event) => updateLocal(account.id, "role", event.target.value)} disabled={!editable} className="rounded-xl border border-slate-200 px-3 py-2 disabled:bg-slate-50">{ERP_ROLES.filter((item) => item === account.role || canManageTargetRole(access?.role, item)).map((item) => <option key={item} value={item}>{ERP_ROLE_LABELS[item as Role]}</option>)}</select><button type="button" onClick={() => void saveAccount(account)} disabled={!editable || savingId !== null} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2 font-black text-slate-700 hover:bg-slate-50 disabled:opacity-40">{savingId === account.discord_id ? <Loader2 size={16} className="animate-spin"/> : <Save size={16}/>}儲存</button></article>; })}</div></>}
  </section>;
}
