import "server-only";
import { getAuthUserFromRequest } from "@/lib/salaryWallet";
import { getErpCapabilities, isErpAdminRole, normalizeErpRole } from "@/lib/erpRoles";
export const ERP_OWNER_DISCORD_ID = "847840193859682304";
const ORGANIZATIONS = { deepnight: { adminTable: "admins" }, qiunai: { adminTable: "qiunai_admins" } };
function organizationConfig(organization) { const config = ORGANIZATIONS[organization]; if (!config) throw new Error("ERP 組織設定不正確"); return config; }
function isMissingRoleTable(error) { const message = String(error?.message || ""); return message.includes("erp_role_assignments") || message.includes("schema cache"); }
export async function getErpAccessByDiscordId(supabaseAdmin, organization, discordId) { const id = String(discordId || "").trim(); if (!id) throw new Error("無法取得 Discord ID"); const config = organizationConfig(organization); const { data: assignment, error: assignmentError } = await supabaseAdmin.from("erp_role_assignments").select("id, organization_code, discord_id, display_name, role, is_active").eq("organization_code", organization).eq("discord_id", id).maybeSingle(); if (assignmentError && !isMissingRoleTable(assignmentError)) throw assignmentError; if (assignment) { const role = assignment.is_active === false ? "employee" : normalizeErpRole(assignment.role); return { discordId: id, assignment, role, isAdmin: assignment.is_active !== false && isErpAdminRole(role), capabilities: getErpCapabilities(role) }; } const { data: legacyAdmin, error: legacyError } = await supabaseAdmin.from(config.adminTable).select("*").eq("discord_id", id).eq("is_active", true).maybeSingle(); if (legacyError) throw legacyError; let role = "employee"; if (legacyAdmin) role = id === ERP_OWNER_DISCORD_ID || legacyAdmin.role === "owner" ? "super_admin" : "store_manager"; return { discordId: id, assignment: null, legacyAdmin, role, isAdmin: Boolean(legacyAdmin) && isErpAdminRole(role), capabilities: getErpCapabilities(role) }; }
export async function authorizeErpRequest(supabaseAdmin, request, organization, capability = "canAccessAdmin") { const auth = await getAuthUserFromRequest(supabaseAdmin, request); const access = await getErpAccessByDiscordId(supabaseAdmin, organization, auth.discordId); if (!access.capabilities[capability]) { const error = new Error("你的 ERP 帳號沒有執行此操作的權限"); error.status = access.isAdmin ? 403 : 401; throw error; } return { ...auth, ...access }; }
export function erpErrorResponse(error, fallback = "ERP 權限驗證失敗") { return Response.json({ ok: false, message: error?.message || fallback }, { status: Number(error?.status || 400) }); }

