create table if not exists public.customer_service_order_points (
  id bigint generated by default as identity primary key,
  app_key text not null check (app_key in ('deepnight', 'qiunai')),
  order_id text not null,
  discord_id text not null,
  points integer not null default 1 check (points > 0),
  served_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (app_key, order_id)
);
create index if not exists customer_service_points_month_idx on public.customer_service_order_points (app_key, served_at desc);
create index if not exists customer_service_points_staff_idx on public.customer_service_order_points (app_key, discord_id, served_at desc);
alter table public.customer_service_order_points enable row level security;
revoke all on table public.customer_service_order_points from anon, authenticated;
grant all on table public.customer_service_order_points to service_role;
grant usage, select on sequence public.customer_service_order_points_id_seq to service_role;
